config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'user/index' => 'user#index'
  get '/' => 'user#index'
  get 'comment/index/:id' => 'comment#index', as:'link_comments'
  get'comment/show/:id' => 'comment#show', as: 'photo_comments'
  get 'photo/index/:id' => 'photo#index', as:'user_photos'
  get 'photo/index/:id' => 'photo#index', as:'link_photos'

  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :photos
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  def index
    @photoid=params[:id]
    @photo=Photo.find_by(id: @photoid)
    @comments=Comment.where(photo_id: @photoid)
    @has_comment=@comments.count>0
    @user=User.find_by(id:@photo.user_id)
  end
  def index_user_name(user_id)
    @user=User.find_by(id:user_id)
    return @user.first_name

  end
  helper_method :index_user_name
end

app/controllers/photo_controller.rb
class PhotoController < ApplicationController
  def index
    @userid=params[:id]
    @user=User.find(params[:id])
    @photos=Photo.where(user_id: params[:id])
     @comments=Comment.where(user_id:params[:id])
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users=User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comment/index.html.erb
<html>
<h1>Comments of User Photo Page
</h1>
<h3>
  Comments of <%=@user.first_name%> <%=@user.last_name%>
</h3>
<style>
  table {
    border-collapse: collapse;
  }
  th, td ,tr{
    border: 1px solid orange;
    padding: 10px;
    text-align: left;
  }
</style>
<body>
<table>

  <% @comments.each do|comment_variable| %>
      <tr>
        <td>
    <p><b>Comment :</b><%=comment_variable.comment_text%></p>
      </td></tr>
      <tr>
      <td>
    <p>Comment Created at <%=comment_variable.date_time%></p>
      </td>
      </tr>
      <tr>
        <td>
          <p>Posted By:<%=link_to index_user_name(comment_variable.user_id),user_photos_path[comment_variable.user_id]%></p>
        </td>
        <%end%>
      </tr>
      </table>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoSite</title>
    <%= csrf_meta_tags %>

    </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photo/index.html.erb
<html>
<head>
<h1>PhotoSite User Photo Page
</h1>
<h3>
<h3> Photos of <%=@user.first_name%> <%=@user.last_name%></h3>
</h3>
<body>
<style>
  table {
    border-collapse: collapse;
  }
  th, td,tr {
    border: 1px solid orange;
    padding: 10px;
    text-align: left;
  }
</style>
<table>
  <tbody>
  <tr>
  <td>
<% @photos.each do|photo_variable| %>

    <%=image_tag(photo_variable.file_name , alt: '#')%>
        </td></tr>
<tr>
  <td>

    <p>Photo Created at <%=photo_variable.date_time%></p>
  </td>
</tr>
        <tr>
          <td>
            <p><%= link_to "Show Comments", link_comments_path(photo_variable.id) %></p>
    <%end%>

</td>
  </tr>
</tbody>

</table>
</body>
</head>
</html>

app/views/user/index.html.erb
<html>
<h1>PhotoSite User Index Page
</h1>
<head >
<h3> There are <%=@users.count%> users</h3>
  <style>
    table {
      border-collapse: collapse;
    }
    th, td {
      border: 1px solid orange;
      padding: 10px;
      text-align: left;
    }
  </style>
<table  >
  <thead>
  <tr>
  <th>User</th>
  <th>First Name</th>
  <th>Last Name</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, link_photos_path(user.id) %></td>
        <td><%=user.first_name%></td>
        <td><%=user.last_name%></td>
      </tr>
  <%end%>
  </tbody>

</table>
</head>
</html>